project: 
  type: website
  output-dir: docs

website:
  page-footer:
    border: false
    left: "{{< meta current_year >}} • Roy Francis"
    right: "Published with [Quarto](https://quarto.org/) v{{< meta quarto_version >}}"
  site-url: "https://royfrancis.github.io/revealjs-header/"

format:
  html:
    title-block-banner: true
    title: revealjs-header
    subtitle: Add logos to revealjs presentation
    description: A quarto extension to add logos to revealjs presentation
    author: Roy Francis
  revealjs:
    title: revealjs-header
    subtitle: Add logos to revealjs presentation
    description: A quarto extension to add logos to revealjs presentation

filters:
  - revealjs-header
  - custom.lua
